networks:
  themesong-network:
    name: themesong-network
    driver: bridge
services:
  cloudflare-ddns:
    env_file:
      - .env
    image: favonia/cloudflare-ddns:latest
    network_mode: host
    restart: always
    user: "1000:1000"
    read_only: true
    cap_drop: [all]
    security_opt: [no-new-privileges:true]
    environment:
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
      - DOMAINS=themesong.io
      - PROXIED=true
  caddy:
    image: caddy:latest
    container_name: themesong-caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - themesong-network
